apiVersion: v1
kind: Service

metadata:
  name: techstore-service

spec:
  selector:
    app: techstore-backend

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

  type: LoadBalancer